In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
def classifier(x):
    if x < -40:
        return 'ea'
    if x <= 0:
        return 'ma'
    if x <= 40:
        return 'mi'
    return 'ei'

In [3]:
path = '..\\Data\\'
random_state = 42
n_features_to_select = 5
n_runs = 100
df_path = path + 'predictions_seed{}_feat{}_runs{}.csv'.format(random_state, n_features_to_select, n_runs)
rfe_path = path + 'rfe_res_seed{}_feat{}_runs{}.pkl'.format(random_state, n_features_to_select, n_runs)

In [4]:
results = pd.read_csv(df_path, header=0, sep=';', decimal=',', index_col=0)

In [5]:
results

,0,5,36,45,13,54,loss
inhibition efficiency ZE41 / %,-157.000000,39.000000,12.000000,-6.000000,38.000000,-17.000000,0.000000
0,-45.158423,21.875755,13.758552,-4.305609,91.188577,-7.848975,0.022013
1,-98.477028,18.075747,54.268172,-7.367241,134.664919,-11.037212,0.021047
2,-98.762306,12.088322,96.671490,-13.535715,129.976549,-19.286000,0.027735
3,-107.675249,0.387588,107.202462,-26.794761,57.022486,-38.569716,0.019949
...,...,...,...,...,...,...,...
95,-93.162170,0.834695,73.539885,-29.261568,85.819381,-36.533142,0.017543
96,-104.666203,2.706866,97.830264,-29.477870,129.501160,-32.452875,0.028825
97,-99.732338,12.990198,63.588853,-25.367308,82.915201,-29.842332,0.012847
98,-106.461223,-8.148041,67.186196,-38.703284,71.795967,-41.229673,0.014873
99,-91.521492,-2.208501,52.655582,-38.607555,55.259953,-41.073502,0.013413

In [6]:
results.describe()

,0,5,36,45,13,54,loss
count,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000
mean,-96.473017,10.251307,74.737901,-19.065389,99.923897,-23.566787,0.020272
std,13.424240,11.337537,21.342983,10.166281,31.759342,12.106045,0.007493
min,-157.000000,-18.192747,2.121534,-43.194884,16.612359,-43.258474,0.000000
25%,-103.284081,2.706866,60.901943,-25.624974,81.666331,-32.991016,0.016323
50%,-97.918619,10.150932,74.994410,-17.906417,95.852173,-25.446746,0.018671
75%,-89.298824,17.141476,88.659300,-13.292689,118.523367,-17.000000,0.022196
max,-45.158423,39.000000,119.808778,5.466224,211.946275,18.115216,0.058345

In [7]:
results[results.index != 'inhibition efficiency ZE41 / %'].describe()

,0,5,36,45,13,54,loss
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,-95.867747,9.963820,75.365280,-19.196043,100.543136,-23.632455,0.020475
std,12.027272,11.018452,20.493135,10.131916,31.300541,12.148940,0.007247
min,-121.698346,-18.192747,2.121534,-43.194884,16.612359,-43.258474,0.008468
25%,-102.603891,2.500443,61.477553,-25.752160,82.602983,-33.134625,0.016477
50%,-97.901118,10.066647,75.137902,-18.317572,96.964389,-25.488980,0.018702
75%,-89.288966,16.965086,88.749808,-13.325708,118.844087,-17.508947,0.022271
max,-45.158423,38.292103,119.808778,5.466224,211.946275,18.115216,0.058345

In [8]:
results[results.index == 'inhibition efficiency ZE41 / %'].applymap(classifier)

                                 0   5  36  45  13  54 loss
inhibition efficiency ZE41 / %  ea  mi  mi  ma  mi  ma   ma

In [9]:
results[results.index != 'inhibition efficiency ZE41 / %'].mean().apply(classifier)

0       ea
5       mi
36      ei
45      ma
13      ei
54      ma
loss    mi
dtype: object