In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
def classifier(x):
    if x < -40:
        return 'ea'
    if x < 0:
        return 'ma'
    if x < 40:
        return 'mi'
    return 'ei'

In [3]:
path = '..\\Data\\'
random_state = 42
n_features_to_select = 5
n_runs = 100
df_path = path + 'predictions_seed{}_feat{}_runs{}.csv'.format(random_state, n_features_to_select, n_runs)
rfe_path = path + 'rfe_res_seed{}_feat{}_runs{}.pkl'.format(random_state, n_features_to_select, n_runs)

In [4]:
results = pd.read_csv(df_path, header=0, sep=';', decimal=',', index_col=0)

In [5]:
results

,0,5,36,45,13,54,loss
inhibition efficiency ZE41 / %,-157.000000,39.000000,12.000000,-6.000000,38.000000,-17.000000,0.000000
0,-67.977380,18.271033,34.897669,-19.885204,89.324541,-19.205017,0.016398
1,-99.585860,12.610203,67.844696,-17.907214,117.775805,-20.460339,0.019085
2,-92.580002,16.002051,96.563071,-11.245806,127.190573,-18.211185,0.027744
3,-113.978378,-11.677962,81.683017,-37.263103,41.829133,-48.855559,0.015797
...,...,...,...,...,...,...,...
95,-99.431828,7.376757,98.838324,-22.702374,105.008652,-30.526447,0.023534
96,-97.420168,-2.132272,92.617895,-32.749018,128.937562,-30.804480,0.029289
97,-100.376435,16.092899,49.405432,-19.300510,114.562138,-20.332937,0.015655
98,-116.474259,-10.187413,61.792093,-38.045631,64.760335,-40.908748,0.012400
99,-105.448852,-10.245524,34.080577,-39.500298,69.000020,-46.738139,0.011955

In [6]:
results.describe()

,0,5,36,45,13,54,loss
count,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000
mean,-97.172655,10.044824,74.170893,-18.595272,102.483933,-22.994931,0.020836
std,12.295236,11.208369,22.444805,10.602673,34.816380,12.698621,0.008527
min,-157.000000,-14.350371,-22.548731,-39.500298,38.000000,-48.855559,0.000000
25%,-104.546891,3.564557,59.884117,-25.013916,80.239723,-30.887312,0.015041
50%,-97.420168,10.712427,77.239712,-18.726110,95.632797,-24.328985,0.018976
75%,-90.700285,16.888599,91.853843,-12.509082,123.941473,-17.949212,0.024858
max,-67.977380,45.494140,115.010673,22.478126,199.555593,20.586675,0.051227

In [7]:
results[results.index != 'inhibition efficiency ZE41 / %'].describe()

,0,5,36,45,13,54,loss
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,-96.574381,9.755272,74.792602,-18.721225,103.128772,-23.054880,0.021044
std,10.778850,10.878561,21.666213,10.579874,34.380267,12.748221,0.008307
min,-116.474259,-14.350371,-22.548731,-39.500298,41.829133,-48.855559,0.007626
25%,-103.740389,3.562592,60.709284,-25.030706,80.480633,-30.887944,0.015203
50%,-97.411514,10.392103,77.322664,-18.831524,95.676409,-24.415966,0.019031
75%,-90.572425,16.802065,91.865412,-12.743412,124.054224,-18.141927,0.024878
max,-67.977380,45.494140,115.010673,22.478126,199.555593,20.586675,0.051227

In [8]:
results[results.index == 'inhibition efficiency ZE41 / %'].applymap(classifier)

                                 0   5  36  45  13  54 loss
inhibition efficiency ZE41 / %  ea  mi  mi  ma  mi  ma   mi

In [9]:
results[results.index != 'inhibition efficiency ZE41 / %'].mean().apply(classifier)

0       ea
5       mi
36      ei
45      ma
13      ei
54      ma
loss    mi
dtype: object

In [10]:
results.std(axis=0)

0       12.295236
5       11.208369
36      22.444805
45      10.602673
13      34.816380
54      12.698621
loss     0.008527
dtype: float64

In [11]:
with open('..\\Data\\rf_results.pkl', 'rb') as f:
    res_dict = pickle.load(f)

In [12]:
for key in res_dict.keys():
    for k in res_dict[key].keys():
        print(key, k)
        print(res_dict[key][k])

(3, 'rf') loss mean
0.05333250686526299
(3, 'rf') loss std
0.024744345941183753
(3, 'rf') pred mean
0     -11.644418
5      35.222423
36      2.077501
45     26.356657
13    121.641020
54    -41.713018
dtype: float64
(3, 'rf') pred std
0     45.985006
5     20.906963
36    25.642445
45    22.198172
13    61.366890
54    28.421437
dtype: float64
(3, 'rfe') loss mean
0.029666505306959152
(3, 'rfe') loss std
0.018543837206979365
(3, 'rfe') pred mean
0    -140.430883
5      63.303661
36     34.826439
45    -22.284843
13    147.957736
54     19.111144
dtype: float64
(3, 'rfe') pred std
0     33.150751
5     18.207593
36    28.932608
45    20.718578
13    52.348472
54    27.658377
dtype: float64
(5, 'rf') loss mean
0.052586213173344734
(5, 'rf') loss std
0.025610854399673512
(5, 'rf') pred mean
0     -12.443432
5      36.881293
36     -2.767877
45     24.083744
13    122.729546
54    -40.527884
dtype: float64
(5, 'rf') pred std
0     46.659880
5     18.869017
36    26.276059
45    21.399793
13    57.321076
54    30.150723
dtype: float64
(5, 'rfe') loss mean
0.029124097982421517
(5, 'rfe') loss std
0.01660491934808318
(5, 'rfe') pred mean
0    -138.899909
5      65.772058
36     32.875376
45    -19.876483
13    144.029941
54     23.678747
dtype: float64
(5, 'rfe') pred std
0     33.190006
5     19.362198
36    29.436711
45    22.357475
13    49.410676
54    31.746329
dtype: float64
(63, 'rf') loss mean
0.05216865622438491
(63, 'rf') loss std
0.026339212784811016
(63, 'rf') pred mean
0     -10.682136
5      31.910694
36     -3.741794
45     21.967358
13    117.044071
54    -41.504530
dtype: float64
(63, 'rf') pred std
0     51.234453
5     19.549449
36    27.688496
45    21.602905
13    55.437519
54    26.169364
dtype: float64
(63, 'rfe') loss mean
0.028964279277715832
(63, 'rfe') loss std
0.018209716274328477
(63, 'rfe') pred mean
0    -142.418804
5      64.897289
36     30.144287
45    -20.625978
13    146.926977
54     18.856074
dtype: float64
(63, 'rfe') pred std
0     32.519561
5     18.399786
36    27.202690
45    19.219678
13    53.767047
54    27.803282
dtype: float64

In [13]:
for key in res_dict.keys():
    print(key)
    prm = ['{:.2f} & '.format(p) for p in res_dict[key]['pred mean']]
    print('  {:.4f} & '.format(res_dict[key]['loss mean']) + ''.join(prm) )
    prs = ['$\pm$ {:.2f} & '.format(p) for p in res_dict[key]['pred std']]
    print('  $\pm$ {:.4f} & '.format(res_dict[key]['loss std'])+ ''.join(prs))

(3, 'rf')
  0.0533 & -11.64 & 35.22 & 2.08 & 26.36 & 121.64 & -41.71 &
  $\pm$ 0.0247 & $\pm$ 45.99 & $\pm$ 20.91 & $\pm$ 25.64 & $\pm$ 22.20 & $\pm$ 61.37 & $\pm$ 28.42 &
(3, 'rfe')
  0.0297 & -140.43 & 63.30 & 34.83 & -22.28 & 147.96 & 19.11 &
  $\pm$ 0.0185 & $\pm$ 33.15 & $\pm$ 18.21 & $\pm$ 28.93 & $\pm$ 20.72 & $\pm$ 52.35 & $\pm$ 27.66 &
(5, 'rf')
  0.0526 & -12.44 & 36.88 & -2.77 & 24.08 & 122.73 & -40.53 &
  $\pm$ 0.0256 & $\pm$ 46.66 & $\pm$ 18.87 & $\pm$ 26.28 & $\pm$ 21.40 & $\pm$ 57.32 & $\pm$ 30.15 &
(5, 'rfe')
  0.0291 & -138.90 & 65.77 & 32.88 & -19.88 & 144.03 & 23.68 &
  $\pm$ 0.0166 & $\pm$ 33.19 & $\pm$ 19.36 & $\pm$ 29.44 & $\pm$ 22.36 & $\pm$ 49.41 & $\pm$ 31.75 &
(63, 'rf')
  0.0522 & -10.68 & 31.91 & -3.74 & 21.97 & 117.04 & -41.50 &
  $\pm$ 0.0263 & $\pm$ 51.23 & $\pm$ 19.55 & $\pm$ 27.69 & $\pm$ 21.60 & $\pm$ 55.44 & $\pm$ 26.17 &
(63, 'rfe')
  0.0290 & -142.42 & 64.90 & 30.14 & -20.63 & 146.93 & 18.86 &
  $\pm$ 0.0182 & $\pm$ 32.52 & $\pm$ 18.40 & $\pm$ 27.20 & $\pm$ 19.22 & $\pm$ 53.77 & $\pm$ 27.80 &

In [14]:
rs = [3, 13, 42, 57, 81]

In [15]:
result = []
indiv = []

In [16]:
for rand in rs:
    rfe_path = path + 'rfe_res_seed{}_feat{}_runs{}.pkl'.format(rand, n_features_to_select, n_runs)
    with open(rfe_path, 'rb') as f:
        rfe_dict = pickle.load(f) #counts, vals
    counts = rfe_dict['counts']
    vals = rfe_dict['vals']
    if rand != random_state:
        df_path = path + 'predictions_seed{}_feat{}_runs{}.csv'.format(rand, n_features_to_select, n_runs)
        with open(df_path, 'rb') as f:
            df_n = pd.read_csv(df_path, header=0, sep=';', decimal=',', index_col=0, skiprows=1)
            df_n.columns = results.columns
            results = results.append(df_n, ignore_index=True)
    for idx in np.where(counts > 0)[0]:
        result.append([rand, counts[idx], sorted(vals[idx])])
        indiv.append('.'.join(sorted(vals[idx])))

In [29]:
results.drop(labels=0, axis=0).describe()

,0,5,36,45,13,54,loss
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,-40.634779,-35.156448,-48.236897,23.210864,-15.653578,-29.131070,0.036200
std,69.778459,53.695676,83.292590,50.541841,73.805054,62.559552,0.028913
min,-170.634803,-178.753510,-171.832253,-66.806782,-134.023607,-171.815884,0.003300
25%,-101.935603,-81.519955,-105.176845,-16.654917,-85.117458,-37.352171,0.011538
50%,-54.433037,-6.011962,-80.910281,12.111062,-14.931941,-19.863083,0.020180
75%,33.861240,8.118763,24.520687,43.968850,18.542225,0.793944,0.066714
max,71.347004,45.494140,115.010673,166.074025,199.555593,75.159306,0.102601

In [18]:
result_df = pd.DataFrame(result, columns=['Seed', 'Count', 'Features'])

In [19]:
result_df

     Seed  Count                                           Features
0       3      1       [E1p, GATS4s, LUMO / eV, Mor04m, P_VSA_MR_5]
1       3      1    [GATS4s, GATS5v, LUMO / eV, Mor04m, P_VSA_MR_5]
2       3      1  [CATS3D_02_AP, GATS5v, LUMO / eV, Mor04m, P_VS...
3       3     12       [E1p, GATS5v, LUMO / eV, Mor04m, P_VSA_MR_5]
4       3      1       [GATS5v, H3m, LUMO / eV, Mor04m, P_VSA_MR_5]
..    ...    ...                                                ...
127    81     58       [E1p, LUMO / eV, Mor04m, Mor22s, P_VSA_MR_5]
128    81      1  [HOMO / eV, LUMO / eV, Mor04m, Mor22s, P_VSA_M...
129    81      1        [E1p, Mor04m, Mor22s, P_VSA_MR_5, SpMAD_RG]
130    81      1       [E1p, LUMO / eV, Mor04m, P_VSA_MR_5, TDB04s]
131    81      3          [E1p, Mor04m, Mor22s, P_VSA_MR_5, TDB04s]

[132 rows x 3 columns]

In [20]:
s = result_df['Features'].str.join('|').str.get_dummies()
s.sum(axis=0).sort_values()

VE2sign_G         1
E3p               1
Mor19m            1
R5p+              1
Hy                1
Mor11u            1
Mor04i            1
GATS4s            2
H3m               2
TDB03m            3
GATS5m            4
MATS5m            7
TDB04s            8
Mor32m            8
MATS5v           10
P_VSA_LogP_2     11
SpMAD_RG         13
GATS5v           15
HOMO / eV        16
Mor14s           22
Mor29v           26
CATS3D_02_AP     35
Mor22s           36
Mor14u           39
E1p              57
Mor04m           91
LUMO / eV       120
P_VSA_MR_5      128
dtype: int64

In [21]:
rr = [set(r[2]) for r in result]

In [22]:
list(set(rr[0]) & set(rr[1]))

['LUMO / eV', 'P_VSA_MR_5', 'GATS4s', 'Mor04m']

In [23]:
a = ['1', 'fsdfs', 'vv']

In [24]:
'.'.join(a)

'1.fsdfs.vv'

In [25]:
len(list(set(indiv)))

103

In [26]:
len(indiv)

132

In [27]:
from collections import Counter

In [28]:
col_counts = {k: v for k, v in sorted(Counter(indiv).items(), key=lambda item: item[1], reverse=True)}
col_counts

{'CATS3D_02_AP.E1p.LUMO / eV.Mor04m.P_VSA_MR_5': 4,
 'E1p.HOMO / eV.LUMO / eV.Mor04m.P_VSA_MR_5': 4,
 'E1p.LUMO / eV.Mor04m.Mor22s.P_VSA_MR_5': 4,
 'HOMO / eV.LUMO / eV.Mor04m.Mor22s.P_VSA_MR_5': 3,
 'LUMO / eV.Mor04m.Mor14s.Mor14u.P_VSA_MR_5': 3,
 'E1p.GATS5v.LUMO / eV.Mor04m.P_VSA_MR_5': 2,
 'GATS5v.LUMO / eV.Mor04m.Mor22s.P_VSA_MR_5': 2,
 'CATS3D_02_AP.E1p.HOMO / eV.LUMO / eV.P_VSA_MR_5': 2,
 'E1p.LUMO / eV.Mor04m.Mor14s.P_VSA_MR_5': 2,
 'E1p.LUMO / eV.Mor04m.Mor29v.P_VSA_MR_5': 2,
 'LUMO / eV.Mor04m.Mor22s.Mor29v.P_VSA_MR_5': 2,
 'E1p.LUMO / eV.Mor04m.Mor32m.P_VSA_MR_5': 2,
 'LUMO / eV.Mor04m.Mor22s.Mor32m.P_VSA_MR_5': 2,
 'CATS3D_02_AP.LUMO / eV.Mor04m.Mor14u.P_VSA_MR_5': 2,
 'E1p.LUMO / eV.Mor04m.Mor14u.P_VSA_MR_5': 2,
 'CATS3D_02_AP.E1p.LUMO / eV.Mor22s.P_VSA_MR_5': 2,
 'E1p.LUMO / eV.Mor04m.P_VSA_MR_5.TDB04s': 2,
 'E1p.LUMO / eV.MATS5m.Mor04m.P_VSA_MR_5': 2,
 'LUMO / eV.MATS5v.Mor04m.Mor22s.P_VSA_MR_5': 2,
 'LUMO / eV.Mor04m.Mor22s.P_VSA_LogP_2.P_VSA_MR_5': 2,
 'CATS3D_02_AP.E1p.HOMO / eV.Mor04m.P_VSA_MR_5': 2,
 'E1p.GATS4s.LUMO / eV.Mor04m.P_VSA_MR_5': 1,
 'GATS4s.GATS5v.LUMO / eV.Mor04m.P_VSA_MR_5': 1,
 'CATS3D_02_AP.GATS5v.LUMO / eV.Mor04m.P_VSA_MR_5': 1,
 'GATS5v.H3m.LUMO / eV.Mor04m.P_VSA_MR_5': 1,
 'GATS5v.LUMO / eV.Mor04m.Mor14s.P_VSA_MR_5': 1,
 'GATS5v.LUMO / eV.Mor04m.Mor29v.P_VSA_MR_5': 1,
 'GATS5v.LUMO / eV.Mor04m.P_VSA_MR_5.SpMAD_RG': 1,
 'GATS5v.LUMO / eV.Mor04m.P_VSA_MR_5.TDB04s': 1,
 'LUMO / eV.MATS5v.Mor04m.Mor14s.P_VSA_MR_5': 1,
 'E1p.LUMO / eV.MATS5v.Mor14s.P_VSA_MR_5': 1,
 'CATS3D_02_AP.LUMO / eV.Mor04m.Mor29v.P_VSA_MR_5': 1,
 'LUMO / eV.Mor04m.Mor14s.Mor29v.P_VSA_MR_5': 1,
 'E1p.LUMO / eV.Mor04m.P_VSA_MR_5.SpMAD_RG': 1,
 'LUMO / eV.Mor04m.Mor22s.P_VSA_MR_5.SpMAD_RG': 1,
 'LUMO / eV.Mor04m.Mor29v.P_VSA_MR_5.SpMAD_RG': 1,
 'CATS3D_02_AP.LUMO / eV.Mor04m.P_VSA_MR_5.TDB04s': 1,
 'E1p.LUMO / eV.Mor14s.P_VSA_MR_5.TDB04s': 1,
 'E1p.LUMO / eV.Mor22s.P_VSA_MR_5.TDB04s': 1,
 'CATS3D_02_AP.GATS5m.LUMO / eV.Mor14u.Mor29v': 1,
 'E1p.GATS5m.LUMO / eV.Mor14u.P_VSA_MR_5': 1,
 'GATS5m.LUMO / eV.Mor14s.Mor14u.P_VSA_MR_5': 1,
 'GATS5m.LUMO / eV.Mor14u.Mor29v.P_VSA_MR_5': 1,
 'GATS5v.LUMO / eV.Mor14u.Mor29v.P_VSA_MR_5': 1,
 'LUMO / eV.MATS5m.Mor14u.Mor22s.P_VSA_MR_5': 1,
 'LUMO / eV.MATS5m.Mor14u.Mor29v.P_VSA_MR_5': 1,
 'LUMO / eV.MATS5m.Mor14u.P_VSA_MR_5.SpMAD_RG': 1,
 'CATS3D_02_AP.LUMO / eV.MATS5v.Mor14s.P_VSA_MR_5': 1,
 'LUMO / eV.MATS5v.Mor14u.Mor29v.P_VSA_MR_5': 1,
 'CATS3D_02_AP.LUMO / eV.Mor14s.Mor14u.Mor29v': 1,
 'LUMO / eV.Mor14s.Mor14u.P_VSA_LogP_2.P_VSA_MR_5': 1,
 'LUMO / eV.Mor04m.Mor14u.Mor29v.P_VSA_MR_5': 1,
 'CATS3D_02_AP.LUMO / eV.Mor14s.Mor14u.P_VSA_MR_5': 1,
 'E1p.LUMO / eV.Mor14s.Mor14u.P_VSA_MR_5': 1,
 'Hy.LUMO / eV.Mor14s.Mor14u.P_VSA_MR_5': 1,
 'CATS3D_02_AP.LUMO / eV.Mor14u.Mor29v.P_VSA_MR_5': 1,
 'LUMO / eV.Mor14s.Mor14u.Mor29v.P_VSA_MR_5': 1,
 'LUMO / eV.Mor14u.Mor22s.Mor29v.P_VSA_MR_5': 1,
 'CATS3D_02_AP.LUMO / eV.Mor14u.Mor32m.P_VSA_MR_5': 1,
 'LUMO / eV.Mor14u.Mor29v.Mor32m.P_VSA_MR_5': 1,
 'CATS3D_02_AP.LUMO / eV.Mor14u.P_VSA_MR_5.SpMAD_RG': 1,
 'LUMO / eV.Mor04m.Mor14u.P_VSA_MR_5.SpMAD_RG': 1,
 'LUMO / eV.Mor14s.Mor14u.P_VSA_MR_5.SpMAD_RG': 1,
 'LUMO / eV.Mor14u.Mor29v.P_VSA_MR_5.SpMAD_RG': 1,
 'LUMO / eV.Mor14s.Mor29v.P_VSA_MR_5.SpMAD_RG': 1,
 'CATS3D_02_AP.LUMO / eV.Mor14u.P_VSA_MR_5.TDB03m': 1,
 'LUMO / eV.Mor14u.Mor32m.P_VSA_MR_5.TDB03m': 1,
 'CATS3D_02_AP.LUMO / eV.Mor14u.Mor29v.SpMAD_RG': 1,
 'LUMO / eV.Mor14u.Mor29v.SpMAD_RG.TDB03m': 1,
 'GATS5v.LUMO / eV.Mor04m.Mor19m.P_VSA_MR_5': 1,
 'GATS5v.Mor04m.Mor14u.Mor22s.P_VSA_MR_5': 1,
 'LUMO / eV.MATS5m.Mor04m.Mor22s.P_VSA_MR_5': 1,
 'LUMO / eV.MATS5v.Mor04m.P_VSA_LogP_2.P_VSA_MR_5': 1,
 'E1p.LUMO / eV.MATS5v.Mor04m.P_VSA_MR_5': 1,
 'HOMO / eV.LUMO / eV.MATS5v.Mor04m.P_VSA_MR_5': 1,
 'CATS3D_02_AP.LUMO / eV.Mor04m.P_VSA_LogP_2.P_VSA_MR_5': 1,
 'E1p.LUMO / eV.Mor04m.P_VSA_LogP_2.P_VSA_MR_5': 1,
 'LUMO / eV.Mor04m.Mor29v.P_VSA_LogP_2.P_VSA_MR_5': 1,
 'Mor04m.Mor22s.Mor29v.P_VSA_LogP_2.P_VSA_MR_5': 1,
 'LUMO / eV.Mor04m.Mor14u.P_VSA_LogP_2.P_VSA_MR_5': 1,
 'E1p.LUMO / eV.Mor04m.P_VSA_MR_5.R5p+': 1,
 'E1p.LUMO / eV.Mor04i.Mor04m.P_VSA_MR_5': 1,
 'HOMO / eV.LUMO / eV.Mor04m.Mor14s.P_VSA_MR_5': 1,
 'LUMO / eV.Mor04m.Mor14s.Mor22s.P_VSA_MR_5': 1,
 'CATS3D_02_AP.LUMO / eV.Mor04m.Mor22s.P_VSA_MR_5': 1,
 'CATS3D_02_AP.LUMO / eV.Mor04m.Mor32m.P_VSA_MR_5': 1,
 'HOMO / eV.LUMO / eV.Mor04m.Mor14u.P_VSA_MR_5': 1,
 'LUMO / eV.Mor04m.Mor14u.Mor22s.P_VSA_MR_5': 1,
 'HOMO / eV.LUMO / eV.Mor04m.P_VSA_MR_5.TDB04s': 1,
 'CATS3D_02_AP.E1p.GATS5v.LUMO / eV.P_VSA_MR_5': 1,
 'CATS3D_02_AP.E1p.LUMO / eV.MATS5v.P_VSA_MR_5': 1,
 'CATS3D_02_AP.E1p.LUMO / eV.P_VSA_LogP_2.P_VSA_MR_5': 1,
 'CATS3D_02_AP.E1p.LUMO / eV.Mor11u.P_VSA_MR_5': 1,
 'CATS3D_02_AP.E1p.LUMO / eV.Mor29v.P_VSA_MR_5': 1,
 'CATS3D_02_AP.E1p.LUMO / eV.P_VSA_MR_5.VE2sign_G': 1,
 'E1p.MATS5m.Mor04m.Mor22s.P_VSA_MR_5': 1,
 'CATS3D_02_AP.E1p.Mor04m.P_VSA_LogP_2.P_VSA_MR_5': 1,
 'CATS3D_02_AP.E1p.Mor04m.Mor22s.P_VSA_MR_5': 1,
 'E1p.E3p.Mor04m.Mor22s.P_VSA_MR_5': 1,
 'E1p.H3m.Mor04m.Mor22s.P_VSA_MR_5': 1,
 'E1p.HOMO / eV.Mor04m.Mor22s.P_VSA_MR_5': 1,
 'E1p.Mor04m.Mor22s.P_VSA_MR_5.SpMAD_RG': 1,
 'E1p.Mor04m.Mor22s.P_VSA_MR_5.TDB04s': 1}