In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('..\\Data\\cv_all_stats.csv', header=0, sep=';', decimal=',', index_col=0)

In [3]:
data

    Index  Features Type       R^2       RMSE         r         p
0       0         3    a  0.923040  39.705129  0.960750  0.009280
1       0         3    b  0.617955  43.100698  0.786101  0.114867
2       0         5    a  0.895742  31.920260  0.946436  0.014761
3       0         5    b  0.691591  40.713181  0.831619  0.080814
4       0        63    a  0.618035  46.283493  0.786152  0.114827
..    ...       ...  ...       ...        ...       ...       ...
65      9         5    a  0.818365  40.299273  0.904635  0.013208
66      9         5    b  0.725170  50.024233  0.851569  0.031412
67      9        63    a  0.833153  36.755630  0.912772  0.011081
68      9        63    b  0.606749  49.508101  0.778941  0.067899
69      9      1260    a  0.540976  60.311789  0.735511  0.095681

[70 rows x 7 columns]

In [4]:
data[(data['Index']!=5)].groupby(['Type', 'Features']).median()

               Index       R^2       RMSE         r         p
Type Features
a    3             4  0.613302  63.972123  0.783136  0.065445
     5             4  0.735557  55.084046  0.857646  0.028955
     63            4  0.608815  46.283493  0.780266  0.073597
     1260          4  0.371949  61.349438  0.609876  0.198607
b    3             4  0.563285  52.528243  0.750523  0.114867
     5             4  0.667411  49.822877  0.816952  0.051281
     63            4  0.606749  49.508101  0.778941  0.067899

In [5]:
data[(data['Index']!=5)].groupby(['Type', 'Features']).mean()

                  Index       R^2       RMSE         r         p
Type Features
a    3         4.444444  0.426820  63.783350  0.536947  0.375736
     5         4.444444  0.607056  53.169413  0.732998  0.164243
     63        4.444444  0.603217  53.856711  0.759468  0.112792
     1260      4.444444  0.487764  64.617320  0.664241  0.196998
b    3         4.444444  0.482053  59.199037  0.659789  0.197975
     5         4.444444  0.574743  56.123730  0.736512  0.131001
     63        4.444444  0.613340  58.638600  0.765733  0.104207

In [51]:
data[(data['Features']==5) & (data['Type']=='b')]

    Index  Features Type       R^2        RMSE         r         p
3       0         5    b  0.691591   40.713181  0.831619  0.080814
10      1         5    b  0.667411   64.652407  0.816952  0.047193
17      2         5    b  0.109156   99.971342  0.330387  0.522451
24      3         5    b  0.239557   64.725589  0.489446  0.324456
31      4         5    b  0.732362   49.822877  0.855781  0.029699
38      5         5    b  0.343786  120.742697  0.586333  0.221287
45      6         5    b  0.726332   40.062603  0.852251  0.031132
52      7         5    b  0.626760   47.375650  0.791682  0.060575
59      8         5    b  0.654346   47.765689  0.808917  0.051281
66      9         5    b  0.725170   50.024233  0.851569  0.031412

In [7]:
import pickle

In [8]:
with open('..\\Data\\anova_cv.pkl', 'rb') as f:
    anova = pickle.load(f)

In [9]:
anova

[('CATS2D_03_AP', 'CATS3D_03_AP', 'CATS3D_02_AP'),
 ('CATS2D_03_AP', 'CATS3D_03_AP', 'CATS3D_02_AP', 'LUMO / eV', 'P_VSA_MR_5'),
 ('CATS2D_03_AP',
  'CATS3D_03_AP',
  'CATS3D_02_AP',
  'LUMO / eV',
  'P_VSA_MR_5',
  'P_VSA_LogP_2',
  'CATS2D_02_PN',
  'CATS2D_03_DP',
  'H3m',
  'nRNH2',
  'H%',
  'Mor14u',
  'CATS2D_03_AN',
  'Eta_epsi_5',
  'CATS3D_03_DP',
  'P_VSA_e_3',
  'Mor19m',
  'Mv',
  'Mor12e',
  'B02[C-N]',
  'Eta_F_A',
  'R2e+',
  'Mor14s',
  'NssCH2',
  'Mor32m',
  'SHED_AP',
  'P_VSA_ppp_con',
  'Mor14v',
  'Mor08s',
  'E2m',
  'SPH',
  'MATS7m',
  'F03[N-O]',
  'SsNH2',
  'CATS3D_04_NL',
  'E3p',
  'Hlgap / eV',
  'CATS2D_04_AA',
  'Mor08i',
  'HOMO / eV',
  'TDB03e',
  'TDB02e',
  'B03[N-O]',
  'CATS3D_02_AN',
  'Mi',
  'Mor27m',
  'TDB04v',
  'ZM2V',
  'Mor12p',
  'Eta_FL_A',
  'GATS1m',
  'Ui',
  'Mor12m',
  'SHED_PN',
  'SHED_DP',
  'GATS1v',
  'MLOGP',
  'MPC07',
  'nN',
  'DLS_05',
  'nArCOOH',
  'Mor08p',
  'SpPosA_B(e)'),
 ('LUMO / eV', 'P_VSA_MR_5', 'CATS2D_03_AP'),
 ('LUMO / eV', 'P_VSA_MR_5', 'CATS2D_03_AP', 'P_VSA_LogP_2', 'R6p+'),
 ('LUMO / eV',
  'P_VSA_MR_5',
  'CATS2D_03_AP',
  'P_VSA_LogP_2',
  'R6p+',
  'Eta_F_A',
  'P_VSA_e_3',
  'H%',
  'MPC07',
  'TDB04v',
  'Mv',
  'ZM2V',
  'D/Dtr06',
  'Eig09_AEA(ed)',
  'Mi',
  'Eta_epsi_5',
  'P_VSA_ppp_con',
  'Eta_beta',
  'nN',
  'nCsp2',
  'TDB05v',
  'N%',
  'R6i+',
  'TDB03r',
  'TDB01v',
  'ZM1Kup',
  'Eta_betaP',
  'TDB04s',
  'GATS1i',
  'ZM2Mad',
  'GGI3',
  'TDB02e',
  'Eig05_AEA(bo)',
  'X4sol',
  'VE1_B(i)',
  'Eig10_AEA(ed)',
  'TDB06e',
  'Eig11_AEA(ed)',
  'Ram',
  'MPC06',
  'GATS1v',
  'nRNH2',
  'X3',
  'GGI4',
  'H_Dz(i)',
  'Eig04_AEA(dm)',
  'Eig06_AEA(bo)',
  'C%',
  'TDB03m',
  'H_Dz(p)',
  'EE_B(m)',
  'TDB06i',
  'Eta_sh_y',
  'X5',
  'MaxDD',
  'Eig06_AEA(dm)',
  'TDB03e',
  'nArCOOH',
  'Eig05_AEA(dm)',
  'piPC05',
  'O%',
  'Wap',
  'ATS4m'),
 ('LUMO / eV', 'CATS3D_02_AP', 'CATS2D_03_AP'),
 ('LUMO / eV', 'CATS3D_02_AP', 'CATS2D_03_AP', 'CATS3D_03_AP', 'SHED_AP'),
 ('LUMO / eV',
  'CATS3D_02_AP',
  'CATS2D_03_AP',
  'CATS3D_03_AP',
  'SHED_AP',
  'P_VSA_e_3',
  'P_VSA_MR_5',
  'HOMO / eV',
  'P_VSA_LogP_2',
  'CATS2D_02_PN',
  'CATS2D_03_DP',
  'SHED_DP',
  'SsNH2',
  'H3m',
  'B02[C-N]',
  'Eta_epsi_5',
  'E3p',
  'SHED_PN',
  'nN',
  'SPH',
  'Mor14u',
  'Mi',
  'CATS3D_03_DP',
  'H%',
  'P_VSA_ppp_con',
  'Mv',
  'Mor12e',
  'CATS3D_04_NL',
  'Hy',
  'nRNH2',
  'Mor14v',
  'MLOGP',
  'Mor14s',
  'Eta_F_A',
  'CATS2D_03_AN',
  'F01[C-N]',
  'Ui',
  'R2e+',
  'Mor08s',
  'N%',
  'TDB04v',
  'Eta_D_epsiD',
  'nHDon',
  'NssCH2',
  'Hlgap / eV',
  'C%',
  'E3v',
  'RDF020m',
  'CATS3D_02_AN',
  'nCsp2',
  'L3u',
  'nCconj',
  'CATS3D_02_AA',
  'E3i',
  'Dp',
  'CATS2D_02_PL',
  'TDB01v',
  'nArCOOH',
  'L3s',
  'F03[N-O]',
  'MEcc',
  'Mor12p',
  'Eta_betaP'),
 ('CATS3D_02_AP', 'LUMO / eV', 'CATS2D_03_AP'),
 ('CATS3D_02_AP', 'LUMO / eV', 'CATS2D_03_AP', 'CATS3D_03_AP', 'P_VSA_MR_5'),
 ('CATS3D_02_AP',
  'LUMO / eV',
  'CATS2D_03_AP',
  'CATS3D_03_AP',
  'P_VSA_MR_5',
  'CATS2D_03_DP',
  'CATS3D_03_DP',
  'P_VSA_LogP_2',
  'CATS2D_02_PN',
  'P_VSA_e_3',
  'Mv',
  'H%',
  'H3m',
  'nRNH2',
  'SHED_AP',
  'E3p',
  'SsNH2',
  'Mi',
  'Eta_F_A',
  'Mor12e',
  'HOMO / eV',
  'Eta_epsi_5',
  'MLOGP',
  'NssCH2',
  'SPH',
  'Mor08i',
  'SHED_DP',
  'Hlgap / eV',
  'C%',
  'CATS2D_03_AN',
  'MPC07',
  'Mor14u',
  'P_VSA_ppp_con',
  'Ui',
  'Mor14v',
  'GATS1m',
  'TDB01v',
  'Mor14s',
  'TDB04v',
  'Mor08p',
  'nArCOOH',
  'B02[C-N]',
  'Eta_betaP',
  'Dp',
  'Hy',
  'Eta_D_epsiD',
  'Mor12p',
  'nCsp2',
  'Mor12m',
  'GATS1i',
  'E3i',
  'Eta_beta',
  'Mor27m',
  'nN',
  'F03[N-O]',
  'RDF020m',
  'AVS_B(e)',
  'ZM2V',
  'DLS_02',
  'GATS1v',
  'Eta_D_epsiB',
  'TDB04s',
  'Mor32m'),
 ('LUMO / eV', 'P_VSA_MR_5', 'CATS3D_02_AP'),
 ('LUMO / eV', 'P_VSA_MR_5', 'CATS3D_02_AP', 'CATS2D_03_DP', 'CATS2D_03_AP'),
 ('LUMO / eV',
  'P_VSA_MR_5',
  'CATS3D_02_AP',
  'CATS2D_03_DP',
  'CATS2D_03_AP',
  'P_VSA_LogP_2',
  'CATS3D_03_AP',
  'CATS3D_03_DP',
  'P_VSA_e_3',
  'nRNH2',
  'Eta_epsi_5',
  'H3m',
  'Eta_F_A',
  'CATS2D_02_PN',
  'Mv',
  'Hlgap / eV',
  'Mi',
  'H%',
  'Mor14u',
  'Mor14s',
  'TDB04v',
  'SsNH2',
  'Eta_sh_y',
  'Ui',
  'TDB04e',
  'CATS2D_03_AN',
  'Mor08p',
  'Mor12e',
  'Mor12m',
  'R2e+',
  'TDB01v',
  'ZM2V',
  'P_VSA_ppp_con',
  'CATS3D_04_NL',
  'GATS1m',
  'Mor32m',
  'C%',
  'CATS3D_02_AL',
  'TDB03r',
  'D/Dtr06',
  'Eta_betaP',
  'B02[C-N]',
  'Mor08i',
  'TDB03e',
  'MLOGP',
  'nN',
  'Eta_beta',
  'Mor05m',
  'Mor08s',
  'nCsp2',
  'NssCH2',
  'HOMO / eV',
  'MPC07',
  'Mor14v',
  'E3p',
  'Hy',
  'ChiA_B(v)',
  'GATS1i',
  'Eta_D_epsiD',
  'JGI5',
  'nArCOOH',
  'Mor27m',
  'RDF020m'),
 ('LUMO / eV', 'CATS3D_02_AP', 'P_VSA_MR_5'),
 ('LUMO / eV', 'CATS3D_02_AP', 'P_VSA_MR_5', 'Mor14s', 'Mor14u'),
 ('LUMO / eV',
  'CATS3D_02_AP',
  'P_VSA_MR_5',
  'Mor14s',
  'Mor14u',
  'CATS2D_03_AP',
  'Hlgap / eV',
  'Eta_sh_y',
  'H3m',
  'Mor08p',
  'Eta_F_A',
  'CATS3D_03_AP',
  'NssCH2',
  'Mor08i',
  'H%',
  'Mor14v',
  'CATS2D_03_DP',
  'P_VSA_LogP_2',
  'P_VSA_e_3',
  'Mor12e',
  'Mor08s',
  'R2e+',
  'Mv',
  'Mor12p',
  'GATS1v',
  'E3p',
  'nArCOOH',
  'ChiA_B(s)',
  'GATS1i',
  'Mor12m',
  'Eta_epsi_5',
  'nN',
  'B02[C-N]',
  'Mor32m',
  'RDF020m',
  'Dp',
  'Mi',
  'Mor15i',
  'CATS2D_03_AN',
  'SPH',
  'Mor26u',
  'MPC07',
  'TDB04s',
  'TDB03e',
  'D/Dtr06',
  'VE1sign_B(m)',
  'Mor19m',
  'CATS3D_02_AL',
  'Eta_betaP',
  'Ui',
  'Eig06_AEA(dm)',
  'O%',
  'nCsp2',
  'L3u',
  'F01[C-N]',
  'DLS_05',
  'ZM2V',
  'GGI4',
  'TDB01v',
  'AVS_B(s)',
  'P_VSA_ppp_con',
  'TDB02e',
  'Mor08v'),
 ('CATS3D_02_AP', 'LUMO / eV', 'CATS2D_03_AP'),
 ('CATS3D_02_AP', 'LUMO / eV', 'CATS2D_03_AP', 'CATS3D_03_AP', 'P_VSA_MR_5'),
 ('CATS3D_02_AP',
  'LUMO / eV',
  'CATS2D_03_AP',
  'CATS3D_03_AP',
  'P_VSA_MR_5',
  'CATS2D_03_DP',
  'P_VSA_LogP_2',
  'Mor12e',
  'CATS2D_02_PN',
  'DLS_02',
  'Eta_epsi_5',
  'H%',
  'P_VSA_e_3',
  'CATS3D_03_DP',
  'Mv',
  'Eta_F_A',
  'Mor12m',
  'Mor12p',
  'E3p',
  'nRNH2',
  'CATS3D_02_AN',
  'CATS3D_02_AA',
  'Hlgap / eV',
  'Mor14s',
  'Mor14v',
  'CATS2D_03_AN',
  'SHED_AP',
  'Mor14u',
  'H3m',
  'DLS_05',
  'R2e+',
  'Mi',
  'SsNH2',
  'TDB04v',
  'RDF020m',
  'Ui',
  'Mor12s',
  'MLOGP',
  'Mor08i',
  'Eta_betaP',
  'Hy',
  'SPH',
  'Mor05m',
  'Eta_FL_A',
  'TDB02e',
  'ZM2V',
  'P_VSA_ppp_con',
  'CATS3D_04_NL',
  'HOMO / eV',
  'GATS1m',
  'nCsp2',
  'TDB01v',
  'TDB03e',
  'Eta_beta',
  'SHED_DP',
  'Dp',
  'L3u',
  'C%',
  'ZM1Kup',
  'MATS7p',
  'D/Dtr06',
  'GATS1v',
  'NssCH2'),
 ('CATS3D_02_AP', 'LUMO / eV', 'CATS2D_03_AP'),
 ('CATS3D_02_AP', 'LUMO / eV', 'CATS2D_03_AP', 'CATS3D_03_AP', 'P_VSA_MR_5'),
 ('CATS3D_02_AP',
  'LUMO / eV',
  'CATS2D_03_AP',
  'CATS3D_03_AP',
  'P_VSA_MR_5',
  'CATS2D_03_AN',
  'CATS2D_03_DP',
  'P_VSA_LogP_2',
  'H3m',
  'CATS2D_02_PN',
  'Eta_epsi_5',
  'P_VSA_e_3',
  'CATS3D_03_DP',
  'nRNH2',
  'H%',
  'CATS3D_02_AN',
  'E3p',
  'CATS2D_04_AA',
  'CATS2D_03_DN',
  'HOMO / eV',
  'B02[C-N]',
  'Mv',
  'Eta_F_A',
  'Mor12e',
  'SHED_AP',
  'CATS3D_04_NL',
  'R2e+',
  'Mor14s',
  'CATS3D_02_AA',
  'Mor14u',
  'SsNH2',
  'TDB02e',
  'TDB03e',
  'O%',
  'nN',
  'Mor08s',
  'Hlgap / eV',
  'B04[O-O]',
  'Mi',
  'ZM2V',
  'TDB04v',
  'H3s',
  'Eta_sh_y',
  'ZM1Kup',
  'Dp',
  'SHED_DP',
  'Mor08p',
  'Mor12m',
  'Eta_D_epsiA',
  'TDB04s',
  'NssCH2',
  'SPH',
  'E2m',
  'MPC07',
  'Mor14v',
  'Mor08i',
  'F02[C-O]',
  'F03[O-O]',
  'P_VSA_ppp_con',
  'Eig06_AEA(dm)',
  'CATS2D_04_DA',
  'Eig06_AEA(bo)',
  'N%'),
 ('CATS3D_02_AP', 'CATS2D_03_AP', 'CATS3D_03_AP'),
 ('CATS3D_02_AP', 'CATS2D_03_AP', 'CATS3D_03_AP', 'CATS2D_03_DP', 'LUMO / eV'),
 ('CATS3D_02_AP',
  'CATS2D_03_AP',
  'CATS3D_03_AP',
  'CATS2D_03_DP',
  'LUMO / eV',
  'P_VSA_MR_5',
  'CATS2D_02_PN',
  'P_VSA_LogP_2',
  'CATS3D_03_DP',
  'P_VSA_e_3',
  'nRNH2',
  'H3m',
  'SHED_AP',
  'B02[C-N]',
  'Eta_epsi_5',
  'SsNH2',
  'TDB03m',
  'CATS2D_03_AN',
  'R2e+',
  'Mv',
  'F03[N-O]',
  'TDB04m',
  'SHED_DP',
  'Mor12e',
  'Mor08s',
  'Eta_F_A',
  'H%',
  'CATS3D_02_AN',
  'CATS2D_04_AA',
  'Mor14u',
  'Mi',
  'SHED_PN',
  'TDB01v',
  'B03[N-O]',
  'CATS2D_03_DN',
  'B04[O-O]',
  'E2s',
  'nN',
  'CATS3D_02_AA',
  'Mor14s',
  'Hlgap / eV',
  'TDB04v',
  'E2m',
  'Eig06_AEA(dm)',
  'CATS3D_04_NL',
  'AMW',
  'SpMAD_RG',
  'N%',
  'MLOGP',
  'E3p',
  'TDB03r',
  'TDB03e',
  'Eig07_AEA(bo)',
  'SM15_AEA(dm)',
  'D/Dtr06',
  'Mor12m',
  'TDB02e',
  'Mor27m',
  'Mor08p',
  'Eig09_AEA(ed)',
  'Mor27s',
  'Mor08i',
  'TDB01m'),
 ('CATS3D_02_AP', 'CATS2D_03_AP', 'CATS3D_03_AP'),
 ('CATS3D_02_AP', 'CATS2D_03_AP', 'CATS3D_03_AP', 'LUMO / eV', 'CATS2D_03_DP'),
 ('CATS3D_02_AP',
  'CATS2D_03_AP',
  'CATS3D_03_AP',
  'LUMO / eV',
  'CATS2D_03_DP',
  'CATS2D_02_PN',
  'P_VSA_MR_5',
  'CATS3D_03_DP',
  'P_VSA_LogP_2',
  'CATS2D_03_AN',
  'H3m',
  'nRNH2',
  'P_VSA_e_3',
  'SHED_AP',
  'Eta_epsi_5',
  'CATS2D_04_AA',
  'SsNH2',
  'Mor14u',
  'Mor14s',
  'CATS3D_04_NL',
  'GGI3',
  'HOMO / eV',
  'Mi',
  'R2e+',
  'SHED_DP',
  'H%',
  'F03[N-O]',
  'Mv',
  'Eta_F_A',
  'MPC07',
  'B04[O-O]',
  'Mor12m',
  'X4sol',
  'Mor12e',
  'ZM2V',
  'TDB04v',
  'nArCOOH',
  'B02[C-N]',
  'Mor08p',
  'D/Dtr06',
  'MLOGP',
  'Mor27m',
  'CATS2D_03_DN',
  'Eta_D_epsiD',
  'NssCH2',
  'JGI5',
  'Mor05m',
  'MATS5m',
  'Mor27s',
  'Eig06_AEA(bo)',
  'Mor14v',
  'Mor32m',
  'Eta_beta',
  'Eig09_AEA(ed)',
  'SHED_PN',
  'B03[N-O]',
  'C%',
  'CATS2D_04_DA',
  'R4m',
  'Qindex',
  'Eig05_AEA(dm)',
  'TDB01v',
  'Hy')]

In [10]:
anova = pd.read_csv('..\\Data\\cv_anova_stats_full.csv', header=0, sep=';', decimal=',', index_col=0)

In [11]:
anova.groupby(['Type', 'Features']).median()

               Index       R^2       RMSE         r         p
Type Features
a    3           4.5  0.341892  67.233201  0.551653  0.287549
     5           4.5  0.571921  61.627276  0.755527  0.083592
     63          4.5  0.418756  70.067546  0.646235  0.166688

In [12]:
data.groupby(['Type', 'Features']).mean()

               Index       R^2       RMSE         r         p
Type Features
a    3           4.5  0.402828  69.804997  0.526485  0.377354
     5           4.5  0.557385  61.212329  0.692917  0.199824
     63          4.5  0.564351  60.892638  0.729842  0.137002
     1260        4.5  0.441023  72.444349  0.612085  0.256042
b    3           4.5  0.465801  65.293934  0.650337  0.202417
     5           4.5  0.551647  62.585627  0.721494  0.140030
     63          4.5  0.616013  63.327350  0.769164  0.099384

In [13]:
data.groupby(['Type', 'Features']).median()

               Index       R^2       RMSE         r         p
Type Features
a    3           4.5  0.400102  66.161448  0.607729  0.228682
     5           4.5  0.675406  56.907921  0.821014  0.046839
     63          4.5  0.600441  50.167522  0.774862  0.082082
     1260        4.5  0.347150  63.039894  0.588818  0.219239
b    3           4.5  0.506952  56.089707  0.710902  0.129596
     5           4.5  0.660879  49.923555  0.812934  0.055928
     63          4.5  0.623408  49.624505  0.789491  0.061938

In [57]:
means_array = data.groupby(['Features','Type']).median()
means_array = means_array[['R^2', 'RMSE', 'r', 'p']].to_numpy()

In [58]:
row_names = ['R^2', 'RMSE', 'r', 'p']
rounds = [2, 0, 2, 2]

In [59]:
for j in range(4):
    r = rounds[j]
    print('%{} & {} & {} & & {} & {} & & {} & {} & & {} \\\\'.format(
    row_names[j], np.round(means_array[0,j],r), np.round(means_array[1,j],r), np.round(means_array[2,j],r), 
        np.round(means_array[3,j],r), np.round(means_array[4,j],r),
        np.round(means_array[5,j],r), np.round(means_array[6,j],r)))

%R^2 & 0.4 & 0.51 & & 0.68 & 0.66 & & 0.6 & 0.62 & & 0.35 \\
%RMSE & 66.0 & 56.0 & & 57.0 & 50.0 & & 50.0 & 50.0 & & 63.0 \\
%r & 0.61 & 0.71 & & 0.82 & 0.81 & & 0.77 & 0.79 & & 0.59 \\
%p & 0.23 & 0.13 & & 0.05 & 0.06 & & 0.08 & 0.06 & & 0.22 \\

In [20]:
means_array

array([[ 0.40282837, 69.80499675,  0.52648481,  0.37735433],
       [ 0.46580081, 65.29393361,  0.6503369 ,  0.20241748],
       [ 0.5573847 , 61.2123293 ,  0.69291698,  0.19982372],
       [ 0.55164715, 62.58562677,  0.72149381,  0.14002998],
       [ 0.56435121, 60.89263821,  0.7298416 ,  0.13700178],
       [ 0.61601302, 63.32735044,  0.76916432,  0.09938368],
       [ 0.44102317, 72.44434863,  0.61208486,  0.25604191]])

In [21]:
data.groupby(['Type', 'Features']).mean()

               Index       R^2       RMSE         r         p
Type Features
a    3           4.5  0.402828  69.804997  0.526485  0.377354
     5           4.5  0.557385  61.212329  0.692917  0.199824
     63          4.5  0.564351  60.892638  0.729842  0.137002
     1260        4.5  0.441023  72.444349  0.612085  0.256042
b    3           4.5  0.465801  65.293934  0.650337  0.202417
     5           4.5  0.551647  62.585627  0.721494  0.140030
     63          4.5  0.616013  63.327350  0.769164  0.099384

In [33]:
data[['Type', 'Features', 'RMSE', 'Index']].groupby(['Type', 'Features']).max()

                     RMSE  Index
Type Features
a    3         123.999817      9
     5         133.598577      9
     63        124.215985      9
     1260      142.887605      9
b    3         120.148007      9
     5         120.742697      9
     63        108.525884      9

In [35]:
arr_data = data[['Type', 'Features', 'RMSE']].to_numpy()

In [47]:
data[(data['Type']=='a') & (data['Features']==5)]['RMSE'].to_numpy()

array([ 31.92025959,  58.73179678,  62.14851387,  84.75910307,
        55.08404585, 133.5985769 ,  62.25753845,  35.44334502,
        47.8808404 ,  40.29927303])

In [41]:
# 3 a
np.array([ 39.70512866,  63.68442063,  68.35077252,
        34.50992412,  63.97212279,  47.52367618,
        79.29587451,  78.10108503]).mean()

59.392875555

In [43]:
# 3 b
np.array([ 43.10069807,  63.12296678,  65.58238571,
        52.52824309,  46.91672814,  59.6511712 ,
        49.70265116,  44.44750954]).mean()

53.13154421125

In [53]:
# 5 c
np.median(np.array([ 55.11925572,  73.32095033,  90.84620209,
        57.76459376,  62.63180503,  45.5214413 ,
        55.17094764,  69.537635  ]))

60.198199395

In [55]:
# 5 b
np.median(np.array([ 40.71318078,  64.65240678,  64.72558857,
        49.82287689,  40.06260347,  47.37564988,
        47.76568919,  50.0242332 ]))

48.79428304

In [56]:
# 5 a 
np.median(np.array([ 31.92025959,  58.73179678,  62.14851387,
        55.08404585 ,  62.25753845,  35.44334502,
        47.8808404 ,  40.29927303]))

51.482443125